sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
git:
  depth: 3
node_js:
  - "6"
  - "8"
before_install:
  - if [[ `npm -v` != 5* ]]; then npm install -g npm@5; fi
install:
  - bundle install --deployment --jobs=3 --retry=3
  - npm install
after_success:
  - if [ "$TRAVIS_REPO_SLUG" = twbs-savage/bootstrap ]; then npm run docs-upload-preview; fi
stages:
  - test
  - name: browser
    if: type = push
cache:
  directories:
    - node_modules
    - vendor/bundle
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
